### ISSUE TITLE
Can’t build doctests using stack

### ISSUE THREAD

**Issue by jtojnar** [ekmett/linear#89]
```
linear-1.20.1: test (suite: doctests)
Progress: 1/2
<command-line>:8:0:
     fatal error: cabal_macros.h: No such file or directory
compilation terminated.
doctests: doctests: phase `C pre-processor' failed (exitcode = 1)
Test suite failure for package linear-1.20.1
    doctests:  exited with: ExitFailure 1
Logs printed to console
```

It seems to start working when I remove the optP arguments but I am not sure if this is a correct way to fix this.I can’t test it with cabal sandbox due to "version of Cabal has changed" bug.

```diff
diff --git a/.ghci b/.ghci
index 231eb17..1295d5a 100644
--- a/.ghci
+++ b/.ghci
@@ -1 +1 @@
-:set -isrc -idist/build/autogen -optP-include -optPdist/build/autogen/cabal_macros.h
+:set -isrc -idist/build/autogen
diff --git a/linear.cabal b/linear.cabal
index bad5e48..298683f 100644
--- a/linear.cabal
+++ b/linear.cabal
@@ -98,7 +98,7 @@ test-suite doctests
   build-depends:
     base,
     directory >= 1.0 && < 1.3,
-    doctest   >= 0.8 && < 0.10,
+    doctest   >= 0.8 && < 0.11,
     filepath  >= 1.3 && < 1.5,
     lens,
     simple-reflect >= 0.3.1
diff --git a/tests/doctests.hs b/tests/doctests.hs
index 6ceefc5..551d1f7 100644
--- a/tests/doctests.hs
+++ b/tests/doctests.hs
@@ -12,8 +12,6 @@ main :: IO ()
 main = getSources >>= \sources -> doctest $
     "-isrc"
   : "-idist/build/autogen"
-  : "-optP-include"
-  : "-optPdist/build/autogen/cabal_macros.h"
   : "-hide-all-packages"
   : map ("-package="++) deps ++ sources
```

**Comment by ekmett** [comment]
We should be able to make this change. I don't use this sort of hack anymore anywhere else in my packages.

**Comment by glguy** [comment]
I my experience problems with cabal versions changed can be resolved by cleaning out `~/.cabal/setup-exe-cache/`

**Comment by jtojnar** [comment]
@glguy I tried nuking the ~/.cabal, .cabal-sandbox and ~/.ghc directories but no luck. According to someone on /r/haskell it should be fixed in cabal 1.24.0 though.

**Comment by jtojnar** [comment]
@ekmett should I make a pull request then or are would you rather switch to Simple build-type completely?

**Comment by glguy** [comment]
Using the following stack.yaml I was able to successfully execute `stack test`. This was after updating the doctest dependency bound. I don't know if that was related.

```
resolver: ghc-7.10

flags:
  text:
    integer-simple: false
extra-deps:
- HUnit-1.3.0.0
- StateVar-1.1.0.1
- adjunctions-4.2.2
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- base-orphans-0.4.4
- bifunctors-5
- bytes-0.15.0.1
- cereal-0.4.1.1
- comonad-4.2.7.2
- contravariant-1.3.3
- distributive-0.4.4
- doctest-0.10.1
- exceptions-0.8.0.2
- extensible-exceptions-0.1.1.4
- free-4.12.1
- ghc-paths-0.1.0.9
- hashable-1.2.3.3
- hostname-1.0
- kan-extensions-4.2.3
- lens-4.13
- mtl-2.2.1
- nats-1
- old-locale-1.0.0.7
- parallel-3.2.0.6
- prelude-extras-0.4.0.2
- primitive-0.6
- profunctors-5.1.1
- random-1.1
- reflection-2.1
- regex-base-0.93.2
- regex-posix-0.95.2
- semigroupoids-5.0.0.4
- semigroups-0.17.0.1
- simple-reflect-0.3.2
- stm-2.4.4
- syb-0.5.1
- tagged-0.8.1
- test-framework-0.8.1.1
- test-framework-hunit-0.3.0.2
- text-1.2.1.3
- transformers-compat-0.4.0.4
- unordered-containers-0.2.5.1
- vector-0.11.0.0
- void-0.7.1
- xml-1.3.14
```

**Comment by jtojnar** [comment]
@glguy you can also use to make things simpler

```
flags:
  linear:
    template-haskell: true
packages:
- '.'
extra-deps: []
resolver: lts-3.5
```
